---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: catalog-service
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: catalog-service@sha256:387456dd7775db5aee0264b1fb432b3629e4f82e52aa539eaa723e8ea32e742d
        namespace: dmanso-coolstore-catalog
      name: latest
